### ISSUE TITLE
Loan Amount issues

### ISSUE THREAD

**Issue by kcaponeAP** [activeprospect/leadconduit-integration-lendio#28] opened 2015-07-09 17:54 UTC
In the Lendio integration, the customer is submitting a range, $5,001 - $25,000 - expressed as %245%2C001+-+%2425%2C000.

Example lead: 
https://next.leadconduit.com/events/559eb2215eecf2ae27ab0a81

However, when the data is received in LCN, it is: Loan Amount = 500125000. 

This is creating an issue for the customer, as all of their leads are being reported as 'over 1 million dollar loans' in their CRM. Can this be addressed swiftly?

Zendesk ticket: https://activeprospect.zendesk.com/agent/tickets/7780

**Comment by alexkwolfe** [comment] 2015-07-09 20:40
The problem is that `loan.amount` is a number field and he's not submitting a number. @ros3bud, can you look at fixing this? I *think* we can change the type on that field to a `range` and that will fix it, but my concern is that it will break something else.

**Comment by alexkwolfe** [comment] 2015-07-09 20:41
Also, this isn't related to the Lendio integration at all. This is a problem on the inbound side. You can tell that because the lead data is wrong. Any time submitted lead data is wrong, it's not a problem with an outbound integration.

**Comment by ros3bud** [comment] 2015-07-09 21:41
Yes, I will look into this.

**Comment by ros3bud** [comment] 2015-07-10 15:13
It does look like changing loan.amount to a range would fix this, however it will indeed break other things. There are 13 integrations using the loan.amount field. Also, Lendio is expecting an ID which is based on where within a range the loan amount falls.

**Comment by alexkwolfe** [comment] 2015-07-10 15:27
Why will changing it break those 13 integrations?

**Comment by ros3bud** [comment] 2015-07-10 15:57
Looking closer, it looks like it won't break all of them. It depends on how the number is being parsed. 

For example, Costco is utilizing parseInt to get the value of amount and passing a range will return NaN.
Also, Lendingtree and Homes.com use regex to replace any symbol or non-digit with an empty string. This could potentially incorrectly concatenate a value such as $100-$200. 

Of the 13 the following would be ok: 
bills.com
leadpoint
lowermybills
military
mortech
velocify

The total integrations I mentioned don't add up to 13 because some include more than 1 export.

**Comment by ros3bud** [comment] 2015-07-29 20:09
Fixed in Version 0.0.21

**Closed by ros3bud** 2015-07-29 20:09 UTC
Labels: enhancement
